export const countryNameToCode: Record<string, string> = {
  // "Andorra": "AND",
  "United Arab Emirates": "ARE",
  "Afghanistan": "AFG",
  // "Antigua and Barbuda": "ATG",
  // "Anguilla": "AIA",
  "Albania": "ALB",
  "Armenia": "ARM",
  "Angola": "AGO",
  // "Antarctica": "ATA",
  "Argentina": "ARG",
  // "American Samoa": "ASM",
  "Austria": "AUT",
  "Australia": "AUS",
  // "Aruba": "ABW",
  // "Åland Islands": "ALA",
  "Azerbaijan": "AZE",
  "French Southern Territories": "ATF",

  "Bosnia and Herzegovina": "BIH",
  // "Barbados": "BRB",
  "Bangladesh": "BGD",
  "Belgium": "BEL",
  "Burkina Faso": "BFA",
  "Bulgaria": "BGR",
  // "Bahrain": "BHR",
  "Burundi": "BDI",
  "Benin": "BEN",
  // "Saint Barthélemy": "BLM",
  // "Bermuda": "BMU",
  "Brunei Darussalam": "BRN",
  "Bolivia, Plurinational State of": "BOL",
  "Brazil": "BRA",
  "Bahamas": "BHS",
  "Bhutan": "BTN",
  // "Bouvet Island": "BVT",
  "Botswana": "BWA",
  "Belarus": "BLR",
  "Belize": "BLZ",

  "Canada": "CAN",
  // "Cocos (Keeling) Islands": "CCK",
  "Congo, Democratic Republic of the": "COD",
  "Central African Republic": "CAF",
  "Congo": "COG",
  "Switzerland": "CHE",
  "Côte d'Ivoire": "CIV",
  // "Cook Islands": "COK",
  "Chile": "CHL",
  "Cameroon": "CMR",
  "China": "CHN",
  "Colombia": "COL",
  "Costa Rica": "CRI",
  "Cuba": "CUB",
  // "Cabo Verde": "CPV",
  // "Curaçao": "CUW",
  // "Christmas Island": "CXR",
  "Cyprus": "CYP",
  "Czechia": "CZE",
  // "Comoros": "COM",
  // "Cayman Islands": "CYM",

  "Germany": "DEU",
  "Djibouti": "DJI",
  "Denmark": "DNK",
  // "Dominica": "DMA",
  "Dominican Republic": "DOM",
  "Algeria": "DZA",

  "Ecuador": "ECU",
  "Estonia": "EST",
  "Egypt": "EGY",
  "Western Sahara": "ESH",
  "Eritrea": "ERI",
  "Spain": "ESP",
  "Ethiopia": "ETH",

  "Finland": "FIN",
  "Fiji": "FJI",
  "Falkland Islands (Malvinas)": "FLK",
  // "Micronesia, Federated States of": "FSM",
  // "Faroe Islands": "FRO",
  "France": "FRA",

  "Gabon": "GAB",
  "United Kingdom of Great Britain and Northern Ireland": "GBR",
  // "Grenada": "GRD",
  "Georgia": "GEO",
  "French Guiana": "GUF",
  // "Guernsey": "GGY",
  "Ghana": "GHA",
  // "Gibraltar": "GIB",
  "Greenland": "GRL",
  "Gambia": "GMB",
  "Guinea": "GIN",
  // "Guadeloupe": "GLP",
  "Equatorial Guinea": "GNQ",
  "Greece": "GRC",
  "Guatemala": "GTM",
  // "Guam": "GUM",
  "Guinea-Bissau": "GNB",
  "Guyana": "GUY",

  // "Hong Kong": "HKG",
  // "Heard Island and McDonald Islands": "HMD",
  "Honduras": "HND",
  "Croatia": "HRV",
  "Haiti": "HTI",
  "Hungary": "HUN",

  "Indonesia": "IDN",
  "Ireland": "IRL",
  "Israel": "ISR",
  // "Isle of Man": "IMN",
  "India": "IND",
  // "British Indian Ocean Territory": "IOT",
  "Iraq": "IRQ",
  "Iran": "IRN",
  "Iceland": "ISL",
  "Italy": "ITA",

  // "Jersey": "JEY",
  "Jamaica": "JAM",
  "Jordan": "JOR",
  "Japan": "JPN",

  "Kenya": "KEN",
  "Kyrgyzstan": "KGZ",
  "Cambodia": "KHM",
  // "Kiribati": "KIR",
  // "Saint Kitts and Nevis": "KNA",
  "South Korea": "KOR",
  "Kuwait": "KWT",
  "Kazakhstan": "KAZ",

  "Lao People's Democratic Republic": "LAO",
  "Lebanon": "LBN",
  // "Saint Lucia": "LCA",
  // "Liechtenstein": "LIE",
  "Sri Lanka": "LKA",
  "Liberia": "LBR",
  "Lesotho": "LSO",
  "Lithuania": "LTU",
  // "Luxembourg": "LUX",
  "Latvia": "LVA",
  "Libya": "LBY",

  "Morocco": "MAR",
  // "Monaco": "MCO",
  "Moldova": "MDA",
  "Montenegro": "MNE",
  // "Saint Martin (French part)": "MAF",
  "Madagascar": "MDG",
  // "Marshall Islands": "MHL",
  "North Macedonia": "MKD",
  "Mali": "MLI",
  "Myanmar": "MMR",
  "Mongolia": "MNG",
  // "Macao": "MAC",
  // "Northern Mariana Islands": "MNP",
  // "Martinique": "MTQ",
  "Mauritania": "MRT",
  // "Montserrat": "MSR",
  // "Malta": "MLT",
  // "Mauritius": "MUS",
  // "Maldives": "MDV",
  "Malawi": "MWI",
  "Mexico": "MEX",
  "Malaysia": "MYS",
  "Mozambique": "MOZ",
  // "Mayotte": "MYT",

  "Namibia": "NAM",
  "New Caledonia": "NCL",
  "Niger": "NER",
  // "Norfolk Island": "NFK",
  "Nigeria": "NGA",
  "Nicaragua": "NIC",
  "Netherlands": "NLD",
  "Norway": "NOR",
  "Nepal": "NPL",
  // "Nauru": "NRU",
  // "Niue": "NIU",
  "New Zealand": "NZL",

  "Oman": "OMN",

  "Panama": "PAN",
  "Peru": "PER",
  // "French Polynesia": "PYF",
  "Papua New Guinea": "PNG",
  "Philippines": "PHL",
  "Pakistan": "PAK",
  "Poland": "POL",
  // "Pitcairn": "PCN",
  "Puerto Rico": "PRI",
  "Palestine": "PSE",
  "Portugal": "PRT",
  // "Palau": "PLW",
  "Paraguay": "PRY",
  "North Korea": "PRK",

  "Qatar": "QAT",

  // "Réunion": "REU",
  "Romania": "ROU",
  "Russia": "RUS",
  "Rwanda": "RWA",

  "Saudi Arabia": "SAU",
  "Solomon Islands": "SLB",
  // "Seychelles": "SYC",
  "Sudan": "SDN",
  "Sweden": "SWE",
  // "Singapore": "SGP",
  // "Saint Helena, Ascension and Tristan da Cunha": "SHN",
  "Slovenia": "SVN",
  // "Svalbard and Jan Mayen": "SJM",
  "Slovakia": "SVK",
  "Sierra Leone": "SLE",
  // "San Marino": "SMR",
  "Senegal": "SEN",
  "Somalia": "SOM",
  "Suriname": "SUR",
  "South Sudan": "SSD",
  // "Sao Tome and Principe": "STP",
  "El Salvador": "SLV",
  // "Sint Maarten (Dutch part)": "SXM",
  "Syrian Arab Republic": "SYR",
  "Eswatini": "SWZ",
  "Serbia": "SRB",
  // "South Georgia and the South Sandwich Islands": "SGS",
  // "Saint Pierre and Miquelon": "SPM",

  // "Turks and Caicos Islands": "TCA",
  "Chad": "TCD",
  "Togo": "TGO",
  "Thailand": "THA",
  "Tajikistan": "TJK",
  // "Tokelau": "TKL",
  "Timor-Leste": "TLS",
  "Turkmenistan": "TKM",
  "Tunisia": "TUN",
  // "Tonga": "TON",
  "Türkiye": "TUR",
  "Trinidad and Tobago": "TTO",
  // "Tuvalu": "TUV",
  "Taiwan, Province of China": "TWN",
  "Tanzania": "TZA",

  "Ukraine": "UKR",
  "Uganda": "UGA",
  // "United States Minor Outlying Islands": "UMI",
  "United States": "USA",
  "Uruguay": "URY",
  "Uzbekistan": "UZB",

  // "Holy See": "VAT",
  // "Saint Vincent and the Grenadines": "VCT",
  "Venezuela, Bolivarian Republic of": "VEN",
  // "Virgin Islands, British": "VGB",
  // "Virgin Islands, U.S.": "VIR",
  "Vietnam": "VNM",
  "Vanuatu": "VUT",

  // "Wallis and Futuna": "WLF",
  // "Samoa": "WSM",

  "Kosovo": "XKX",

  "Yemen": "YEM",

  "South Africa": "ZAF",
  "Zambia": "ZMB",
  "Zimbabwe": "ZWE",
}